/script if UnitMana("Player") < 1000 then use("Major Mana Potion") end;
/script if UnitMana("Player") < 1000 then use("Superior Mana Potion") end;
/decursive
/script if (UnitHealth("player") / UnitHealthMax("player")) < 0.9 then if (UnitHealth("player") / UnitHealthMax("player")) < 0.2 then ClearTarget(); CastSpellByName("Power Word: Shield") CastSpellByName("Flash Heal") SpellTargetUnit("player"); end; if ((UnitHealthMax("player"))-(UnitHealth("player"))) > 1900 then ClearTarget(); CastSpellByName("Flash Heal") SpellTargetUnit("player"); end; if ((UnitHealthMax("player"))-(UnitHealth("player"))) > 600 then ClearTarget(); CastSpellByName("Heal(rank 3)") SpellTargetUnit("player"); end end;
/target samsage
/script if buffed("Mortal Strike", "target") and not buffed("Weakened Soul", "target") then cast("Power Word: Shield") SpellTargetUnit("target"); end
/script if ((UnitHealthMax("target"))-(UnitHealth("target"))) > 500 then if UnitIsPlayer("target") then CastSpellByName("Greater Heal(rank 1)"); end end

/script ClearTarget(); if GetRaidRosterInfo(1) then for i=1,40 do ri=math.random(1,GetNumRaidMembers()); if (UnitHealth("raid"..ri) / UnitHealthMax("raid"..ri)) < 0.9 and CheckInteractDistance("raid"..ri, 4) then if (UnitHealth("raid"..ri) / UnitHealthMax("raid"..ri)) < 0.2 then CastSpellByName("Flash Heal"); SpellTargetUnit("raid"..ri); end; if ((UnitHealthMax("raid"..ri))-(UnitHealth("raid"..ri))) > 1900 then cast("Inner Focus") cast("Greater Heal(rank 2)"); SpellTargetUnit("raid"..ri); end; if ((UnitHealthMax("raid"..ri))-(UnitHealth("raid"..ri))) > 600 then cast("Heal(rank 3)"); end; SpellTargetUnit("raid"..ri); end end; else for i=1,4 do if (UnitHealth("party"..i) / UnitHealthMax("party"..i)) < 0.9 and CheckInteractDistance("party"..i, 4) then if (UnitHealth("party"..i) / UnitHealthMax("party"..i)) < 0.2 then CastSpellByName("Flash Heal"); SpellTargetUnit("party"..i); end; if ((UnitHealthMax("party"..i))-(UnitHealth("party"..i))) > 1900 then cast("Inner Focus") cast("Greater Heal(rank 2)"); SpellTargetUnit("party"..i); end; if ((UnitHealthMax("party"..i))-(UnitHealth("party"..i))) > 600 then cast("Heal(rank 3)"); end; SpellTargetUnit("party"..i); end end; end;

/script i=1;c=0; if GetRaidRosterInfo(1) then while (i <= GetNumRaidMembers()) do if (UnitHealth("raid"..i) / UnitHealthMax("raid"..i)) < 0.75 then c=c+1; end; i=i+1;end; end;