/script if not buffed("Power Word: Fortitude", "player") then cast("Power Word: Fortitude") SpellTargetUnit("player"); end
/target shadeshade
/script if not buffed("Power Word: Fortitude", "target") then cast("Power Word: Fortitude") SpellTargetUnit("target"); end
/script if (UnitHealth("target") / UnitHealthMax("target")) < 0.75 then CastSpellByName("Flash Heal(rank 5)"); end
/decursive
/script for i=1,40 do TargetNearestFriend(); if UnitHealth("target")/UnitHealthMax("target") < 0.8 then if UnitIsPlayer("target") then CastSpellByName("Flash Heal(rank 5)"); end end end;
/assist shadeshade
/script if UnitIsPlayer("target") then CastSpellByName("Shadow Word: Pain"); end
/script if UnitIsPlayer("target") then CastSpellByName("shoot"); end
/script if UnitIsTapped("target") then CastSpellByName("shoot"); end
/follow shadeshade

--/script i=1;c=0; if GetRaidRosterInfo(1) then while (i <= GetNumRaidMembers()) do if (UnitHealth("raid"..i) / UnitHealthMax("raid"..i)) < 0.75 then c=c+1; end; i=i+1;end; end;
--/script ClearTarget(); if (UnitHealth("player") / UnitHealthMax("player")) < 0.9 then if (UnitHealth("player") / UnitHealthMax("player")) < 0.2 then CastSpellByName("Nature's Swiftness") CastSpellByName("Healing Wave") SpellTargetUnit("player"); end; if c >= 3 and (UnitHealth("player") / UnitHealthMax("player")) < 0.8 then CastSpellByName("Chain Heal") SpellTargetUnit("player"); end; if (UnitHealthMax("player") - UnitHealth("player")) > 1900 then CastSpellByName("Lesser Healing Wave") SpellTargetUnit("player"); end; if (UnitHealthMax("player") - UnitHealth("player")) > 600 then CastSpellByName("Lesser Healing Wave(Rank 4)") SpellTargetUnit("player"); end end;
--/script ClearTarget(); if GetRaidRosterInfo(1) then for i=1,40 do ri=math.random(1,GetNumRaidMembers()); if (UnitHealth("raid"..ri) / UnitHealthMax("raid"..ri)) < 0.9 and CheckInteractDistance("raid"..ri, 4) then if (UnitHealth("raid"..ri) / UnitHealthMax("raid"..ri)) < 0.2 then CastSpellByName("Nature's Swiftness") CastSpellByName("Healing Wave"); SpellTargetUnit("raid"..ri); end; if c >= 3 then CastSpellByName("Chain Heal"); SpellTargetUnit("raid"..ri); end; if ((UnitHealthMax("raid"..ri))-(UnitHealth("raid"..ri))) > 1900 then cast("Lesser Healing Wave"); SpellTargetUnit("raid"..ri); end; if ((UnitHealthMax("raid"..ri))-(UnitHealth("raid"..ri))) > 600 then cast("Lesser Healing Wave(Rank 4)"); end; SpellTargetUnit("raid"..ri); end end; else for i=1,4 do if (UnitHealth("party"..i) / UnitHealthMax("party"..i)) < 0.9 and CheckInteractDistance("party"..i, 4) then if (UnitHealth("party"..i) / UnitHealthMax("party"..i)) < 0.2 then CastSpellByName("Nature's Swiftness") CastSpellByName("Healing Wave"); SpellTargetUnit("party"..i); end; if ((UnitHealthMax("party"..i))-(UnitHealth("party"..i))) > 1900 then cast("Lesser Healing Wave"); SpellTargetUnit("party"..i); end; if ((UnitHealthMax("party"..i))-(UnitHealth("party"..i))) > 600 then cast("Lesser Healing Wave(Rank 4)"); end; SpellTargetUnit("party"..i); end end; end;
